In [2]:
#panda nos permite manipular el archivo csv https://pandas.pydata.org
import pandas as pd
#numpy nos permite hacer operaciones usando vectores https://numpy.org
import numpy as np
#plotly nos permite crear graficas interactivas https://plotly.com/python/
import plotly.express as px
%matplotlib inline
#usamos la liga que está directamente en la página.
particles = pd.read_csv('https://opendata.cern.ch/record/5208/files/Zmumu.csv',delimiter=',')
particles.head()

,Run,Event,pt1,eta1,phi1,Q1,dxy1,iso1,pt2,eta2,phi2,Q2,dxy2,iso2
0,165617,74969122,54.7055,-0.4324,2.5742,1,-0.0745,0.4999,34.2464,-0.9885,-0.4987,-1,0.0712,3.4221
1,165617,75138253,24.5872,-2.0522,2.8666,-1,-0.0554,0.0000,28.5389,0.3852,-1.9912,1,0.0515,0.0000
2,165617,75887636,31.7386,-2.2595,-1.3323,-1,0.0879,0.0000,30.2344,-0.4684,1.8833,1,-0.0876,0.0000
3,165617,75779415,39.7394,-0.7123,-0.3123,1,0.0585,0.0000,48.2790,-0.1956,2.9703,-1,-0.0492,0.0000
4,165617,75098104,41.2998,-0.1571,-3.0408,1,-0.0305,1.2280,43.4508,0.5910,-0.0428,-1,0.0442,0.0000

In [4]:
fig_5=px.histogram(particles['pt1'],particles['pt1'])
m_in_category = pd.cut(particles['pt1'], bins=[0, 150], labels=['Momento transversal'])
fig_5=px.histogram(particles['pt1'],particles['pt1'], color=m_in_category, labels={'x': 'Momento transversal', 'color':''})
fig_5.update_layout(
    xaxis_title="$P_{T}[GeV]$",
    yaxis_title="Frecuencia"
)
fig_5.show()

In [152]:
#Se establecen los bins convenientes para limpiar nuestros datos.
phi = (-np.pi, np.pi)
eta = (-2.1, 2.1)
pt = (35, 90)
fil_particles = particles[(particles['eta1'].between(*eta)) 
                          & (particles['eta2'].between(*eta))
                          & (particles['phi1'].between(*phi))
                          & (particles['pt1'].between(*pt))
                          & (particles['pt2'].between(*pt))
                          & (particles['phi2'].between(*phi))
                          & ((particles['Q1'] * particles['Q2']) == -1)]

fil_particles.head()

,Run,Event,pt1,eta1,phi1,Q1,dxy1,iso1,pt2,eta2,phi2,Q2,dxy2,iso2
3,165617,75779415,39.7394,-0.7123,-0.3123,1,0.0585,0.0000,48.2790,-0.1956,2.9703,-1,-0.0492,0.0000
4,165617,75098104,41.2998,-0.1571,-3.0408,1,-0.0305,1.2280,43.4508,0.5910,-0.0428,-1,0.0442,0.0000
5,165617,77255513,38.9425,0.3522,-2.2649,-1,0.0384,0.0000,39.8616,0.2630,0.9183,1,-0.0407,0.0000
6,165617,76042048,42.8278,-0.9549,-0.2418,-1,0.0513,0.6926,48.9864,-1.2183,2.8399,1,-0.0545,2.2525
8,165617,77076988,38.1511,-0.8702,1.7165,1,-0.0840,0.0000,37.8959,0.5000,-1.8676,-1,0.0652,0.0000

In [153]:
fig_5=px.histogram(fil_particles['pt1'],fil_particles['pt1'])

fig_5.show()

In [154]:
ev = len(fil_particles)
print(ev)

4512

In [187]:
combined_df = pd.DataFrame({
    'Transverse Momentum (pt)': pd.concat([fil_particles['pt1'], fil_particles['pt2']]),
    'Tipo': ['pt1'] * len(fil_particles) + ['pt2'] * len(fil_particles)
})


fig = px.histogram(combined_df, x='Transverse Momentum (pt)', color='Tipo', labels={'x': 'Momentp transversal', 'color':''}, title="Comparación de pt1 y pt2", barmode='overlay')
fig.update_xaxes(range=[33, 80])
fig.update_layout(
    xaxis_title='$P_T$ [GeV]',
    yaxis_title='Frecuencia'
)
fig.show()

In [174]:
combined_df = pd.DataFrame({
    'Carga (Q)': pd.concat([fil_particles['Q1'], fil_particles['Q2']], ignore_index=True),
    'Tipo': ['Q1'] * len(fil_particles) + ['Q2'] * len(fil_particles)
})

fig = px.histogram(combined_df, x='Carga (Q)', color='Tipo', title="Distribución de las Cargas de los Muones", barmode='overlay')

fig.update_xaxes(range=[-3, 3])
fig.update_yaxes(range=[0, 3000])


fig.update_layout(
    xaxis_title='Carga (Q)',
    yaxis_title='Frecuencia'
)
moda_q1 = particles['Q1'].mode()[0]
moda_q2 = particles['Q2'].mode()[0]

print(f'Moda de Q1: {moda_q1}')
print(f'Moda de Q2: {moda_q2}')
fig.show()

Moda de Q1: -1
Moda de Q2: 1

In [156]:
def m_inv(pt1,pt2,eta1,eta2,phi1,phi2):
    return np.sqrt(2*pt1*pt2*(np.cosh(eta1-eta2)-np.cos(phi1-phi2)))
m_in = m_inv(fil_particles['pt1'],fil_particles['pt2'],fil_particles['eta1'],fil_particles['eta2'],fil_particles['phi1'],fil_particles['phi2'])
bins = [0, 150]
labels = ['masa invariante']
m_in_category = pd.cut(m_in, bins=bins, labels=labels)
fig_5=px.histogram(m_in, color=m_in_category, labels={'x': 'Masa invariante', 'color':''})
fig_5.update_layout(
    xaxis_title="$M_{T}[GeV]$",
    yaxis_title="Frecuencia"
)
fig_5.show()

In [172]:
md = pd.DataFrame(m_in)

# Calcular estadísticas
median_values = md.median()
std_values = md.std()
var_values = md.var()
mean_values = md.mean()  # Promedio


# Imprimir resultados
print("Mediana:", median_values)
print("\nDesviación estándar:\n", std_values)
print("\nVarianza:\n", var_values)
print("\nPromedio:\n", mean_values)

Mediana: 0    91.010795
dtype: float64

Desviación estándar:
 0    4.876908
dtype: float64

Varianza:
 0    23.784229
dtype: float64

Promedio:
 0    91.211333
dtype: float64